[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"Jinja2==3.1.2",
	"matplotlib==3.7.1",
	"onnx-tf==1.10.0",
	"pandas==2.0.1",
	"scipy==1.10.1",
	"tensorflow-probability==0.19.0",
	"tensorflowjs==4.4.0",
]

[project.optional-dependencies]
dev = [
	"mypy==1.2.0",
	"ruff==0.0.264",
]
