[project]
dependencies = [
  "Jinja2==3.1.2",
  "matplotlib==3.8.0",
  "onnx-tf==1.10.0",
  "pandas==2.1.1",
  "scipy==1.11.2",
  "tensorflow-probability==0.19.0",
  "tensorflowjs==4.4.0"
]
name = "UNKNOWN"
version = "0.0.0"

[project.optional-dependencies]
dev = [
  "coverage==7.3.2",
  "djlint==1.34.0",
  "mypy==1.6.1",
  "ruff==0.1.2",
  "ssort==0.11.6",
  "toml-sort==0.23.1"
]
