[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"Jinja2==3.1.2",
	"matplotlib==3.7.2",
	"onnx-tf==1.10.0",
	"pandas==2.0.3",
	"scipy==1.11.2",
	"tensorflow-probability==0.19.0",
	"tensorflowjs==4.4.0",
]

[project.optional-dependencies]
dev = [
	"black==22.12.0",
	"djlint==1.32.1",
	"mypy==1.5.1",
	"ruff==0.0.287",
	"ssort==0.11.6",
]
