[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"Jinja2==3.1.2",
	"matplotlib==3.7.0",
	"onnx-tf==1.10.0",
	"pandas==1.5.3",
	"scipy==1.10.1",
	"tensorflow-probability==0.19.0",
	"tensorflowjs==4.2.0",
]

[project.optional-dependencies]
dev = [
	"mypy==1.1.1",
	"ruff==0.0.255",
]
