name: test-reproducible-build-and-upload-release
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Test whether the paper is reproducible
        run: make test ARGS=--full GPU= INTERACTIVE=
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: ./ms.pdf
  release:
    if: contains(github.event.commit_head.message, '{release}')
    needs: test
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }} 
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1
          release_name: ${{ github.event.head_commit.message }} v1
          draft: false
          prerelease: false
  upload-release-assets:
    needs: [release]
    runs-on: ubuntu-20.04
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Create sha256sum var
        run: echo "::set-env name=sha256sumvar::$(sha256sum output/ms.pdf | cut -d ' ' -f 1)"
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }} 
          asset_path: ./output/ms.pdf
          asset_name: output-${{ env.sha256sumvar }}.pdf
          asset_content_type: application/pdf
