name: tests
on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'Dockerfile'
      - 'Makefile'
      - 'main.py'
      - 'requirements.txt'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'Dockerfile'
      - 'Makefile'
      - 'main.py'
      - 'requirements.txt'

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Test
        run: make tmp/texlive-test
      - name: git commands for index.html
        run: |
          git add index.html
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --exit-code || git commit -m "update index.html"
          git push
