name: tests
on:
  push:
    paths-ignore:
      - 'docs/'
  pull_request:
    paths-ignore:
      - 'docs/'

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Test
        run: make
