on: [push, pull_request]

jobs:
  develop:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd docs/ && make clean check all && cd ..
          cd latex/python/ && make clean check all && cd ../..
          cd latex/ && make clean check all && cd ..
