on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Check code and build
        run: |
          cd docs/ && make clean check all && cd ..
          cd python/ && make clean check all && cd ..
          make clean check all
