on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Check code and build
        run: |
          cd docs/ && make check all && cd ..
          cd python/ && make check all && cd ..
          make check all
      - name: Test binaries reproducibility
        run: |
          cp bin/ms.pdf bin/ms-first-run.pdf
          touch python/main.py ms.tex
          cd python/ && make && cd ..
          make
          cmp bin/ms.pdf bin/ms-first-run.pdf
