on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Check code and build binaries for html.
        run: |
          make -f Makefile.html check
          make -f Makefile.html
      - name: Check code and build binaries for python.
        run: |
          make -C python/ check
          make -C python/
      - name: Check code and build binaries for tex.
        run: |
          make check
          make
      - name: Test binaries reproducibility.
        run: |
          cp bin/ms.pdf bin/ms-first-run.pdf
          touch python/main.py ms.tex
          make -C python/
          make
          cmp bin/ms.pdf bin/ms-first-run.pdf
