on: [push, pull_request, workflow_dispatch]
jobs:
  develop:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          make clean check all -C docs/
          sed -i 's/torch-bin/torchWithoutCuda/' latex/python/flake.nix
          sed -i 's/torchvision-bin/torchvision/' latex/python/flake.nix
          sed -i 's/config.allowUnfree = true;//' latex/python/flake.nix
          make clean check all -C latex/python/
          make clean check all -C latex/
          make clean check all
